src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une autre annonce possède déjà ce titre, merci de le modifier"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères !", maxMessage="Le titre ne peut pas faire plus de 255 caractères")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description ne peut pas faire moins de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PostLike", mappedBy="post")
     */
    private $likes;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if(empty($this->slug))
        {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une annonce
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach ($this->comments as $comment) {
            if ($comment->getAuthor() === $author) return $comment;
        }

        return null;
    }

    /**
     * Permet d'obtenir la moyenne globale des notes pour cette annonce
     *
     * @return float
     */
    public function getAvgRatings()
    {
        // Calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function ($total, $comment) {
            return $total + $comment->getRating();
        }, 0);

        // Faire la division pour avoir la moyenne
        if (count($this->comments) > 0) return $sum / count($this->comments);

        return 0;
    }


    /**
     * Permet d'obtenir un tableau des jours qui ne sont pas disponibles pour cette annonce
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupation
     */
    public function getNotAvailableDays()
    {
        $notAvailableDays = [];

        foreach ($this->bookings as $booking) {
            // Calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimestamp) {
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PostLike[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(PostLike $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setPost($this);
        }

        return $this;
    }

    public function removeLike(PostLike $like): self
    {
        if ($this->likes->contains($like)) {
            $this->likes->removeElement($like);
            // set the owning side to null (unless already changed)
            if ($like->getPost() === $this) {
                $like->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ImageType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AdType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration("Titre", "Entrez un titre"))
            ->add('slug', TextType::class, $this->getConfiguration("Adresse Web", "Entrez une adresse (auto)", ['required' => false]))
            ->add('coverImage', UrlType::class, $this->getConfiguration("URL de l'image", "Entrez l'adresse de l'image"))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction", "Entrez une description"))
            ->add('content', TextareaType::class, $this->getConfiguration("Description", "Entrez une description"))
            ->add('price', MoneyType::class, $this->getConfiguration("Prix par nuit", "Indiquez un prix"))
            ->add('rooms', IntegerType::class, $this->getConfiguration("Nombre de chambres", "Nombres de chambres disponible"))
            ->add('images', CollectionType::class, [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use App\Repository\AdRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {

        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads,
        ]);
    }

      /**
     * Permet de crée une annonce
     * 
     * @Route("/ads/new", name="ads_create")
     * 
     * @IsGranted("ROLE_USER")
     * 
     * @return Response
     */
    public function create(Request $request, EntityManagerInterface $manager)
    {
        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrée"
            );


            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le formulaire d'édition
     * 
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * 
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas")
     * 
     * @return Response
     */
    public function edit(Ad $ad, Request $request, EntityManagerInterface $manager)
    {
        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $manager->persist($image);
            }
            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success',
                "Les modifications de l'annonce <strong>{$ad->getTitle()}</strong> ont bien été enregistrée"
            );


            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * Permet d'afficher une seule reponse
     * 
     * @Route("/ads/{slug}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad)
    {
        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}
<div class="col-md-4">
	<div class="card bg-light mb-3">
		<div class="card-header text-center">
			{{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ') }} &euro; / nuit</strong><br>
			{% if ad.comments|length > 0 %}
				{% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
			{% else %}
				<small>Pas encore noté</small>
			{% endif %}
		</div>
		<a href="{{ url }}"><img src="{{ ad.coverImage }}" alt=""
				style="height: 200px; width: 100%; display:block;"></a>
		<div class="card-body">
			<h4 class="new-title">
				<a href="{{ url }}">{{ ad.title }}</a>
			</h4>
			<p class="card-text">{{ ad.introduction }}</p>
			<a href="" class="btn btn-link">
				<i class="far fa-thumbs-up"></i>
				<span class="js-likes"></span>
				<span class="js-label">J'aime</span>
			</a>
			<a href="{{ url }}" class="btn btn-primary float-right">Voir</a>
			{% if app.user and app.user == ad.author %}
			<a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier</a>
			{% endif %}
		</div>
	</div>
</div>

templates/ad/_collection.html.twig
{% block _ad_images_widget %}
	<p>Ici, vous pouvez ajouter vos propres images !</p>

	{{ form_widget(form) }}

	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-image" class="btn btn-primary">
			<i class="fas fa-plus"></i>
			Ajouter une image
		</button>
	</div>
{% endblock %}

{% block _ad_images_entry_row %}
	{{ form_widget(form) }}
{% endblock %}

{% block _ad_images_entry_widget %}
	<div class="form-group" id="block_{{id}}">
		{{ form_errors(form) }}
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
						{{ form_errors(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
						{{ form_errors(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
			</div>
		</div>
	</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="container">
    <h1>Modifier l'annonce : {{ ad.title }}</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Modifier</button>
    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-5">Les annonces</h1>
    <div class="row">
        {% for ad in ads %}
        {% include 'ad/_ad.html.twig' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}
<div class="container">
    <h1 class="my-5">Créer une nouvelle annonce</h1>
    {{ form_start(form) }}
    <div class="row">
        <div class="col">
            <div class="alert alert-light">
                <h2>Informations Générales</h2>
                <hr>
                {{ form_row(form.title) }}
                {{ form_row(form.slug) }}
                {{ form_row(form.price) }}
                {{ form_row(form.rooms) }}
            </div>
            <div class="alert alert-light">
                <h2>Détails de l'annonce</h2>
                <hr>
                {{ form_row(form.introduction) }}
                {{ form_row(form.content) }}
            </div>
        </div>
        <div class="col">
            <div class="alert alert-light">
                <h2>Images de l'annonce</h2>
                <hr>
                {{ form_row(form.coverImage) }}
                {{ form_row(form.images) }}
            </div>
        </div>
    </div>
    <div class="alert alert-success clearfix">
        <h2 class="alert-heading">Sauvegarder mon annonce</h2>
        <p>Vous êtes sur le point de crée une annonce</p>
        <button type="submit" class="btn btn-primary float-right">Créer</button>
    </div>
    {{ form_end(form) }}
</div>
{% endblock %}

{% block javascripts %}
    <script src="/js/ad.js"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ ad.title }}
{% endblock %}

{% block body %}<br>
<div class="new-title" style="width: 100%; background-image: url('{{ ad.coverImage }}');">
    <div class="container">
        <h1>{{ ad.title }}</h1>
        <p>{{ ad.introduction }}</p>
        <p class="h2"><strong>{{ ad.rooms }} chambres</strong> pour<strong> {{ ad.price | number_format(2, ',', ' ') }} € </strong>/ nuit</p>
        <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary">Réserver</a>
        {% if app.user and app.user == ad.author %}
        <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier</a>
        <a href="{{ path('ads_delete', {'slug': ad.slug}) }}"
            onclick="return confirm(`Etes vous sur de vouloir supprimer : {{ ad.title }}`)"
            class="btn btn-danger">Supprimer</a>
        {% endif %}
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 mb-3">
            {{ ad.content | raw}}
            <div class="bd-example">
                <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                        <li data-target="#carouselExampleCaptions" data-slide-to="{{ loop.index0 }}"
                            {% if loop.first %}class="active" {% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                        <div class="carousel-item {% if loop.first %} active {% endif %}">
                            <img src="{{ image.url }}" class="d-block w-100" alt="...">
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{ image.caption }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <hr>
            {% if ad.comments|length > 0 %}
                <h2 class="mb-3">Commentaires de nos voyageurs :</h2>
                <div class="alert alert-info">
                    <h4 class="alert-heading text-center">
                        <div class="row align-items-center">
                            <div class="col">
                                Note globale
                            </div>
                            <div class="col">
                                {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                                <br>
                                <small>(Calculée sur {{ ad.comments|length }} avis)</small>
                            </div>
                        </div>
                    </h4>
                </div>

                {% for comment in ad.comments %}
                    <div class="bg-light rounded mb-3 py-3 px-3">
                        <strong>{{ comment.author.firstName }}</strong>
                        a dit :
                        <blockquote>
                            {{comment.content}}
                        </blockquote>
                        <strong>Note donnée :
                        </strong>

                        {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                    </div>
                {% endfor %}
            {% else %}
                <h2>Cette annonce n'a pas encore reçu de commentaires ...</h2>
            {% endif %}

        </div>
        <div class="col">
            {% set a = ad.author %}
            <div class="row mb-3 align-items-center">
                <div class="col-3">
                    <a href="{{ path('user_show', {'slug': a.slug}) }}">
                        <img src="{{ a.picture }}" class="avatar avatar-medium" alt="Avatar de {{ a.fullname }}">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path('user_show', {'slug': a.slug}) }}">
                        <h3>{{ a.fullname }}</h3>
                    </a>
                    <span class="badge badge-primary">{{ a.ads | length }} annonces</span>
                </div>
            </div>
            {{ a.description | raw }}
        </div>
    </div>
</div>
{% endblock %}